Prod (#14)
* chore: Transform src/index.js to TypeScript and rename to index.ts

* chore: Transform src/constants/statusCodes.js to TypeScript and rename to statusCodes.ts

* chore: Transform src/constants/userModel.js to TypeScript and rename to userModel.ts

* chore: Transform src/constants/user.routes.js to TypeScript and rename to users.routes.ts

* chore: Transform src/constants/rating.routes.js to TypeScript and rename to rating.routes.ts

* chore: Transform src/constants/profile.routes.js to TypeScript and rename to profile.routes.ts

* chore: Transform src/constants/movies.routes.js to TypeScript and rename to movies.routes.ts

* chore: Transform src/constants/messages.routes.js to TypeScript and rename to messages.routes.ts

* chore: Transform src/constants/comments.routes.js to TypeScript and rename to comments.routes.ts

* chore: Transform src/constants/auth.routes.js to TypeScript and rename to auth.routes.ts

* chore: Grouped imports for better readability

* chore: Transform src/models/ratingModel.js to TypeScript and rename to ratingModel.ts

* chore: Transform src/models/messageModel.js to TypeScript and rename to messageModel.ts

* chore: Transform src/models/commentModel.js to TypeScript and rename to commentModel.ts

* chore: Transform src/middlware/winston.js to TypeScript and rename to winston.ts

* fix: Fix exports

* chore: Transform src/middlware/validator.js to TypeScript and rename to validator.ts

* chore: Transform src/middlware/notFound.js to TypeScript and rename to notFound.ts

* chore: Transform src/middlware/healthCheck.js to TypeScript and rename to healthCheck.ts

* chore: Transform src/boot/database/db_connect.js to TypeScript and rename to db_connect.ts

* feat: Declared export type

* fix: Removed deprecated cofig

* feat: Declared export type

* chore: Transform comments.controller.js to TypeScript and rename to comments.controller.ts

* chore: Transform commitlint.config.js to TypeScript and rename to commitlint.config.ts

* fix: Included commitlint.config.ts

* feat: Add new dependencies and declare types

* feat: Implemented logger instead of console.log

* mock workflow added

* Update PR-workflow.yml

* Update PR-workflow.yml

* scripts moved on top

* test update PR-workflow.yml

* Update PR-workflow.yml, checkout added

* test deleted

* chore: Transform middleware/authentication.js to TypeScript and rename authentication.ts

* chore: Transform controllers/users.controller.js to TypeScript and rename users.controller.ts

* chore: Transform controllers/rating.controller.js to TypeScript and rename rating.controller.ts

* chore: Transform controllers/profile.controller.js to TypeScript and rename profile.controller.ts

* chore: Transform controllers/movies.controller.js to TypeScript and rename movies.controller.ts

* chore: Transform controllers/messages.controller.js to TypeScript and rename messages.controller.ts

* chore: Transform controllers/auth.controller.js to TypeScript and rename auth.controller.ts

* chore: Update package.json to start index.ts

* chore: Transform src/boot/setup.js to TypeScript and rename setup.ts

* feat: Updated winston loogger write

* feat: Added folder for global declaration of types

* feat: Implemented the usage of global types

* feat: Ignoring to push logs

* feat: Part of the types rework

* fix: Correct export of functions

* fix: Correct import of logger

* fix: Correct import of logger

* fix: Correct import of logger and proper export of functions

* fix: Correct import of logger, proper export of functions and fixed logout function implementation

* fix: Correct import of logger, proper export of functions and fixed returns

* fix: Correct import of logger

* fix: Correct import of logger and stream from winston

* fix: Correct import of logger and environement variables

* fix: TypeError: res.status is not a function

* feat: Tests, linter and build scripts for workflow added

* fix: File fixed

* fix: Workflow and gitignore updated

* feat: Added remote mongo Cluster

---------

Co-authored-by: ciugiu <corneliu.ciugurean@epita.fr>